// <auto-generated />
using System;
using FRS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FRS.Migrations
{
    [DbContext(typeof(ContextCS))]
    partial class ContextCSModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FRS.Models.AdminLogin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("AName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("AdminId");

                    b.ToTable("TblAdminLogin");
                });

            modelBuilder.Entity("FRS.Models.AiroPlaneInfo", b =>
                {
                    b.Property<int>("Planeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Planeid"));

                    b.Property<int>("APlaneName")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.HasKey("Planeid");

                    b.ToTable("PlaneInfo");
                });

            modelBuilder.Entity("FRS.Models.FlightBooking", b =>
                {
                    b.Property<int>("bid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bid"));

                    b.Property<DateTime>("DDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DTime")
                        .HasMaxLength(15)
                        .HasColumnType("datetime2");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("PlaneInfoPlaneid")
                        .HasColumnType("int");

                    b.Property<int>("Planeid")
                        .HasColumnType("int");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("bid");

                    b.HasIndex("PlaneInfoPlaneid");

                    b.ToTable("TblFlightBook");
                });

            modelBuilder.Entity("FRS.Models.UserAccount", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CPassword")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int>("EmailId")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<int>("FirstName")
                        .HasMaxLength(40)
                        .HasColumnType("int");

                    b.Property<int>("LastName")
                        .HasMaxLength(40)
                        .HasColumnType("int");

                    b.Property<string>("NIC")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Password")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("Phoneno")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("UserId");

                    b.ToTable("TblUserAccount");
                });

            modelBuilder.Entity("FRS.Models.FlightBooking", b =>
                {
                    b.HasOne("FRS.Models.AiroPlaneInfo", "PlaneInfo")
                        .WithMany()
                        .HasForeignKey("PlaneInfoPlaneid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaneInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
